### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ahmed-alaa** [event-engine/php-engine-utils#5]
Hello,

Thanks for the applied changes in [e633e2](https://github.com/event-engine/php-engine-utils/commit/e633e24a758cbfcfbbcae6be1fafb9345b00c44f).

Does it require a new release? as last tag was 2021.

Thanks :)

**Comment by codeliner** [comment]
New release available. Thx @ahmed-alaa for the reminder. Best, Alex
